# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e2cbf395e600e07c354f4cd29726020f0d4eb994c11fc3eb189ffbdf215cccd4ed470b72c4c4b6ab955b0cf4c1205741096b25ccba71b2d5889068cefc732d

test:
  secret_key_base: 8a0b3757ce4324828bd45976a5fce6d74ecae7de51df2ea7fd7e3d76dd36df497b99cc7f19ec4d6df4841deabb5fe461c490a78ab087682aff516fcdb1d26a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
